version: '3'
services:
  cassandra-seed:
    image: cassandra:latest
    container_name: cassandra-c01
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_CLUSTER_NAME=Formation

  cassandra-node02:
    image: cassandra:latest
    container_name: cassandra-node02
    environment:
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_CLUSTER_NAME=Formation
    depends_on:
      - cassandra-seed

  cassandra-node03:
    container_name: cassandra-node03
    image: cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_CLUSTER_NAME=Formation
    depends_on:
      - cassandra-node02
